services:
  postgres:
    image: postgres:17
    container_name: multi-vendor-saas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1259
      POSTGRES_DB: multi_vendor_saas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: