packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@scarf/scarf': false
  '@ffmpeg-installer/linux-x64': true
  '@ffprobe-installer/linux-x64': true
  argon2: true
  esbuild: false
  msgpackr-extract: false
  unrs-resolver: false
