import request from 'supertest';
import { describe, it, expect, vi, beforeEach } from 'vitest';

import app from '../../app.js';
import { AppError } from '../../shared/errors/AppError.js';
import { redis } from '../../shared/redis/redis.client.js';

import * as googleService from './google.service.js';

vi.mock('./google.service.js', () => ({
  getGoogleAuthUrl: vi.fn(),
  handleGoogleCallback: vi.fn(),
}));

describe('Google OAuth API (/api/auth/google)', () => {
  beforeEach(async () => {
    vi.clearAllMocks();
    process.env.WEB_ORIGIN = 'http://localhost:3000';
    await redis.flushall();
  });

  /* -------------------------------------------------------------------------- */
  /*                             GET /api/auth/google                           */
  /* -------------------------------------------------------------------------- */
  describe('GET /api/auth/google', () => {
    it('should redirect to Google authorization URL generated by service with from param', async () => {
      const mockAuthUrl =
        'https://accounts.google.com/o/oauth2/v2/auth?client_id=test-id&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fapi%2Fauth%2Fgoogle%2Fcallback&response_type=code&scope=openid+email+profile&state=mock-state';

      vi.mocked(googleService.getGoogleAuthUrl).mockResolvedValueOnce(mockAuthUrl);

      const res = await request(app)
        .get('/api/auth/google')
        .query({ redirect: '/dashboard', from: '/signup' });

      expect(res.status).toBe(302);
      expect(res.headers.location).toBe(mockAuthUrl);
      expect(googleService.getGoogleAuthUrl).toHaveBeenCalledWith('/dashboard', '/signup');
    });

    it('should forward service errors to global error handler', async () => {
      vi.mocked(googleService.getGoogleAuthUrl).mockRejectedValueOnce(
        new AppError(500, 'GOOGLE_CONFIG_MISSING', 'Google OAuth credentials missing'),
      );

      const res = await request(app).get('/api/auth/google');

      expect(res.status).toBe(500);
      expect(res.body.error).toBe('Google OAuth credentials missing');
    });
  });

  /* -------------------------------------------------------------------------- */
  /*                        GET /api/auth/google/callback                       */
  /* -------------------------------------------------------------------------- */
  describe('GET /api/auth/google/callback', () => {
    it('should redirect to signin with error if oauthError query param is present', async () => {
      const res = await request(app)
        .get('/api/auth/google/callback')
        .query({ error: 'access_denied' });

      expect(res.status).toBe(302);
      expect(res.headers.location).toBe('http://localhost:3000/signin?error=access_denied');
    });

    it('should redirect to signin with error if code or state is missing', async () => {
      const res = await request(app).get('/api/auth/google/callback').query({ code: 'valid-code' }); // missing state

      expect(res.status).toBe(302);
      expect(res.headers.location).toBe('http://localhost:3000/signin?error=invalid_request');
    });

    it('should successfully handle callback, set auth_token cookie, and redirect to destination', async () => {
      const mockResult = {
        token: 'mock-jwt-token-12345',
        user: {
          userId: 'user-uuid-1',
          fullName: 'Google User',
          email: 'googleuser@example.com',
          roles: ['customer' as const],
          emailVerifiedAt: new Date(),
        },
        redirectUrl: '/shop',
      };

      vi.mocked(googleService.handleGoogleCallback).mockResolvedValueOnce(mockResult);

      const res = await request(app)
        .get('/api/auth/google/callback')
        .query({ code: 'valid-google-code', state: 'valid-redis-state' });

      expect(res.status).toBe(302);
      expect(res.headers.location).toBe('http://localhost:3000/shop');

      const cookies = res.headers['set-cookie'] as unknown as string[];
      expect(cookies).toBeDefined();
      const authCookie = Array.isArray(cookies)
        ? cookies.find((c) => c.startsWith('auth_token='))
        : cookies;
      expect(authCookie).toBeDefined();
      expect(authCookie).toContain('mock-jwt-token-12345');
      expect(authCookie).toContain('HttpOnly');
    });

    it('should redirect to signup with error if state had fromUrl=/signup and oauthError occurred', async () => {
      await redis.set('oauth_state:signup-state', JSON.stringify({ fromUrl: '/signup' }));

      const res = await request(app)
        .get('/api/auth/google/callback')
        .query({ error: 'access_denied', state: 'signup-state' });

      expect(res.status).toBe(302);
      expect(res.headers.location).toBe('http://localhost:3000/signup?error=access_denied');
    });

    it('should redirect to signin with error message when service throws AppError (e.g. invalid state)', async () => {
      vi.mocked(googleService.handleGoogleCallback).mockRejectedValueOnce(
        new AppError(400, 'INVALID_OAUTH_STATE', 'Authentication session expired or invalid.'),
      );

      const res = await request(app)
        .get('/api/auth/google/callback')
        .query({ code: 'valid-code', state: 'expired-state' });

      expect(res.status).toBe(302);
      expect(res.headers.location).toBe(
        'http://localhost:3000/signin?error=Authentication%20session%20expired%20or%20invalid.',
      );
    });

    it('should redirect to signup with error message when service throws AppError and state had fromUrl=/signup', async () => {
      await redis.set('oauth_state:signup-state-error', JSON.stringify({ fromUrl: '/signup' }));
      vi.mocked(googleService.handleGoogleCallback).mockRejectedValueOnce(
        new AppError(403, 'EMAIL_NOT_VERIFIED', 'Google account email is not verified.'),
      );

      const res = await request(app)
        .get('/api/auth/google/callback')
        .query({ code: 'valid-code', state: 'signup-state-error' });

      expect(res.status).toBe(302);
      expect(res.headers.location).toBe(
        'http://localhost:3000/signup?error=Google%20account%20email%20is%20not%20verified.',
      );
    });
  });
});
